### ISSUE TITLE
[Hacktoberfest] Python IDE

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/starter.lvim#2]
- formatters
- linters
- debugging
- branch name python-ide

**Comment by SingularisArt** [comment]
I'll try and get this done by the end of either today or tomorrow

**Comment by SingularisArt** [comment]
Complete. https://github.com/LunarVim/starter.lvim/pull/9#issue-1393907278

**Comment by RudolfVonKrugstein** [comment]
Thanks for these great setups!

When I take the python setup as it is, I get:

```
This function requires 3 argument(s) but instead receiving 1.
```

On this line:

```
local mason_path = vim.fn.glob(vim.fn.stdpath "data" .. "/mason/")
```

My setup is neovim 0.8 and the latest version of LunarVim.

**Comment by RudolfVonKrugstein** [comment]
Ok, stupid me. While the mentioned line was marked, it was not the cause of the error. That was a misconfiguration on my side. Please ignore my comment :).
