### ISSUE TITLE
How to debug in python

### ISSUE THREAD

**Issue by 3288103265** [LunarVim/starter.lvim#48]
When i debug python file, lvim raise "No configuration found for 'python', You need to add configs to 'dap.configurations.python'(see `-h: dap-configuration`)". I tried to copy https://github.com/LunarVim/starter.lvim/tree/python-ide to ~/.config/lvim/python.lua, but not working. 

So, which file should I config and how to do it?

**Comment by miwojc** [comment]
make backup of your config.lua
```
cd /Users/usern_name/.config/lvim/config.lua
mv config.lua config.lua.bak
```
copy [config.lua](https://github.com/LunarVim/starter.lvim/blob/python-ide/config.lua) from this repo python-ide branch 
```
git clone https://github.com/LunarVim/starter.lvim.git
cd starter.lvim
git switch python-ide
cp config.lua ~/.config/lvim/
```
install requirements
`pip install requirements.txt`
start lunar vim
run `:MasonInstall debugpy` command
run `:PackerSync` command
