### ISSUE TITLE
My confusion  about the rust-ide ide config .

### ISSUE THREAD

**Issue by void-0612** [LunarVim/starter.lvim#73]
https://github.com/LunarVim/starter.lvim/blob/b0b041265d4c1f5f9213b742bd9e00be763a2a6e/config.lua#L8C1-L13
```
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "rust_analyzer" })

local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  { command = "stylua", filetypes = { "lua" } },
}

```

In there，why don't  use the rust_analyzer as default server and use stylua as formatter in rust's config?

**Comment by LostInTheLogs** [comment]
Rust analyzer is used, I have no idea why stylua is there

**Comment by void-0612** [comment]
but this commend seems remove the rust analyzer as default lsp and i've to download it by myself

**Comment by LostInTheLogs** [comment]
It disables the default configuration. This config uses rust tools for configuration instead

**Comment by void-0612** [comment]
> It disables the default configuration. This config uses rust tools for configuration instead

yes,but it not auto download in my computer and i download it by myself ,then  it  can work

**Comment by LostInTheLogs** [comment]
Yes, because it's not using our lsp manager

**Comment by void-0612** [comment]
> 
but in the page of rust-tools,it say it use rust-analyzer,so my confusion is,in this config the author remove the auto download rust-analyzer,but it still need download

**Comment by LostInTheLogs** [comment]
auto download is a feature of our lsp manager, this config disables the lsp manager for rust analyzer with `vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "rust_analyzer" })` and is using rust tools for configuring rust analyzer instead, rust tools doesn't automatically install rust analyzer

**Comment by void-0612** [comment]
oh,i may know,is automatic_configuration is not only download rust_analyzer but also make some config，so we need to remove the config and download by myself?

**Comment by LostInTheLogs** [comment]
yes, mason unfortunately doesn't support ensure_installed so for now you need to download it manually

**Comment by void-0612** [comment]
ok，thanks for your  answer

**Comment by salimp2009** [comment]
we should remove that . it is probably typo from the original implementer. we really dont need to specify formatter too. Rust-analyzer  does that .

**Comment by salimp2009** [comment]
this can be closed since stylua is removed from the config since PR #77 removed . this should be closed now

**Comment by RuggeroRebellato** [comment]
guys, i think this issue should be closed.
